### ISSUE TITLE
issue with installation 

### ISSUE THREAD

**Issue by mcmib** [vmware/vsphere-automation-sdk-python#414] opened 2024-03-04 18:37 UTC
### Describe the bug

Hello bros,

I got issue with installation after execution of the following command:
pip install -U vsphere-automation-sdk-python-8.0.2.0.zip

The following is the detailed information about the issue:
Defaulting to user installation because normal site-packages is not writeable
Processing d:\downloads\vsphere-automation-sdk-python-8.0.2.0.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in vsphere-automation-sdk setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after URL and whitespace)
          vapi-runtime @ file://localhost/C:\Users\mcmib\AppData\Local\Temp\pip-req-build-xy4cima9/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


### Reproduction steps

pip install -U vsphere-automation-sdk-python-8.0.2.0.zip

### Expected behavior

Smooth installation

### Additional context

_No response_

**Comment by shwetapurohit** [comment] 2024-03-06 05:45
@mcmib 
Unable to reproduce this issue.
Whats the python version you are using?

**Comment by shwetapurohit** [comment] 2024-03-18 06:36
There is no update. Closing the issue.
Please feel free to reopen the issue if it persists.

**Closed by shwetapurohit** 2024-03-18 06:36 UTC
Labels: bug
