### ISSUE TITLE
Erroneous import in vmware/vapi/vmc/client.py from vapi-vmc-client==2.9.0 package

### ISSUE THREAD

**Issue by Lucas-C** [vmware/vsphere-automation-sdk-python#71] opened 2018-06-08 12:04 UTC
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk package version: 
```
$ pip freeze | grep vapi
vapi-common-client==2.9.0
vapi-runtime==2.9.0
vapi-vmc-client==2.9.0
```

- python version:
```
$ python --version
Python 2.7.13
```

- wheel package used: https://github.com/vmware/vsphere-automation-sdk-python/tree/346f5b1/lib/vapi-common-client

## Steps or code snippet to reproduce + Actual behavior
```
$ ipython -c 'from vmware.vapi.vmc.client import create_vmc_client'
---------------------------------------------------------------------------                                                                                                 ImportError                               Traceback (most recent call last)
<ipython-input-1-fad65e76a271> in <module>()                                                                                                                                ----> 1 from vmware.vapi.vmc.client import create_vmc_client
                                                                                                                                                                            /home/lucas_cimon/.local/share/virtualenvs/infralib-py2/lib/python2.7/site-packages/vmware/vapi/vmc/client.py in <module>()
      8 import requests                                                                                                                                                           9
---> 10 from com.vmware.vmc_client import StubFactory                                                                                                                            11 from vmware.vapi.bindings.stub import ApiClient
     12 from vmware.vapi.lib.connect import get_requests_connector                                                                                                          
ImportError: No module named com.vmware.vmc_client
```

## Expected behavior
No `ImportError` raised.

## Resolution
Simply replace the 2 following lines in `vmware/vapi/vmc/client.py`:
```
from com.vmware.vmc.client import StubFactory
from vmware.vapi.bindings.stub import ApiClient
```

By:
```
from vmware.vapi.bindings.stub import ApiClient, StubFactory
```

**Comment by dungla2011** [comment] 2018-11-19 16:21
I have the same error!

![image](https://user-images.githubusercontent.com/7878963/48720170-bf40c800-ec51-11e8-8637-84a3a04611c9.png)

... ImportError: No module named vsphere.client

**Comment by tianhao64** [comment] 2018-11-20 02:34
@dungla2011 The binding version you installed(2.5.0) is not the latest and thus you don't see vmware.vapi.vsphere module. Once you installed the correct version 1.5.0, you should see the module. 

@Lucas-C The StubFactory should come from com.vmware.vmc.client. The pip dependencies issue is tracked by https://github.com/vmware/vsphere-automation-sdk-python/issues/70. Closing this as not a bug.

**Closed by tianhao64** 2018-11-20 02:34 UTC
