### ISSUE TITLE
Repo documentation errors

### ISSUE THREAD

**Issue by MsJamie** [vmware/vsphere-automation-sdk-python#368] opened 2023-04-14 02:58 UTC
### Describe the bug

In the example code
https://github.com/vmware/vsphere-automation-sdk-python/tree/v8.0.0.1#connect-to-a-vcenter-server

This has

`from vmware.vapi.vsphere.client import create_vsphere_client`

However it should be `from vmware.vapi.vsphere.client import create_vsphere_client as vsphere_client`

Otherwise you get the message `NameError: name 'vsphere_client' is not defined`

### Reproduction steps

1. Run the example code at https://github.com/vmware/vsphere-automation-sdk-python/tree/v8.0.0.1#connect-to-a-vcenter-server with a valid vcenter IP and credentials
2.
3.
...

### Expected behavior

You should see a python list output containing the Summary of the registered VMs on the cluster

### Additional context

A different issue but minor at the Photon OS downloads are at a different location but the section that mentions

• Copy the [Photon OS](https://vmware.github.io/photon/) ISO image downloaded from [VMware's bintray server](https://dl.bintray.com/vmware/photon) to the datastore

Clicking on the the VMware bintray server URL just provides a 404. That server appears to no longer function. Linking to the new downloads page https://github.com/vmware/photon/wiki/Downloading-Photon-OS seems like a good option instead.

**Comment by shwetapurohit** [comment] 2023-04-14 06:39
@MsJamie 

I'm not able to reproduce this issue. Please let me know how you execute ?

**Comment by shwetapurohit** [comment] 2023-04-24 05:29
There is no update from the user, therefore, closing the bug for now.
Please feel free to reopen if the issue persists

**Closed by shwetapurohit** 2023-04-24 05:29 UTC
Labels: bug
