### ISSUE TITLE
SDK Install from Instructions: Error finding vapi-runtime

### ISSUE THREAD

**Issue by kurasoe** [vmware/vsphere-automation-sdk-python#292] opened 2021-11-03 17:15 UTC
I am using the latest SDK (or trying to), and haven't even got to the point of trying to authenticate to vCenter. I have searched existing issues. I searched old issues and found a few things but those issues were fairly old it seemed.

## Environment
- sdk package version: 
Trying to install per the documentation / README.md at https://github.com/vmware/vsphere-automation-sdk-python, meaning the latest version via "pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git".

- python version: 3.6.8

- vSphere version: 7.0.2

- Operating System/Shell (used to run SDK-based apps): CentOS 7

## Steps or code snippet to reproduce
- Install CentOS 7.2003 Minimal on VMware VM.

- Install python3:
sudo yum -y install python3

- Create and activate venv:
python3 -m venv <name>
cd <name>
source ./bin/activate

- Following instructions, update pip and setuptools:
pip install --upgrade pip setuptools

- Following instructions, attempt install:
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git

## Actual behavior
Full output, error near bottom:

Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /tmp/pip-ubq0vit8-build
Collecting lxml>=4.3.0 (from vSphere-Automation-SDK==1.71.0)
  Using cached https://files.pythonhosted.org/packages/a8/fe/56385f42495bfaf005d1e694a33622718a18d1ea4b6491b32be6461d8158/lxml-4.6.4-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Requirement already up-to-date: pyVmomi>=6.7 in ./lib/python3.6/site-packages (from vSphere-Automation-SDK==1.71.0)
Collecting vapi-runtime@ file://localhost//tmp/pip-ubq0vit8-build/lib/vapi-runtime/vapi_runtime-2.30.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.71.0)
  Could not find a version that satisfies the requirement vapi-runtime@ file://localhost//tmp/pip-ubq0vit8-build/lib/vapi-runtime/vapi_runtime-2.30.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.71.0) (from versions: )
No matching distribution found for vapi-runtime@ file://localhost//tmp/pip-ubq0vit8-build/lib/vapi-runtime/vapi_runtime-2.30.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.71.0)

## Expected behavior
Successful install...

**Comment by shwetapurohit** [comment] 2021-11-08 08:06
I could not reproduce  this  issue neither in centos 7 or ubuntu.

**Comment by kurasoe** [comment] 2021-11-10 16:21
Weird, I see vapi-client-bindings in requirements.txt.

But I get an error suggesting it is not available? Is this not on PyPI?

$ pip3 download vapi-client-bindings
ERROR: Could not find a version that satisfies the requirement vapi-client-bindings (from versions: none)
ERROR: No matching distribution found for vapi-client-bindings

I don't see anything in the requirements.txt that would point it to a different repo, unless I'm missing something.

I am running inside a virtual environment per recommendations in the docs, but the above pip3 command gives the same result regardless.

**Comment by kurasoe** [comment] 2021-11-10 16:24
Weird it seems to have worked today............. I did not change anything on my side though.

**Comment by booboothefool** [comment] 2021-11-10 16:24
I am having this issue on some machines, but it is working on other machines, and I'm not sure what the difference is. I thought it was the Python version at first, but that appears to not be the case.

**Comment by shwetapurohit** [comment] 2021-11-10 16:27
> Weird, I see vapi-client-bindings in requirements.txt.
> 
> But I get an error suggesting it is not available? Is this not on PyPI?
> 
> $ pip3 download vapi-client-bindings ERROR: Could not find a version that satisfies the requirement vapi-client-bindings (from versions: none) ERROR: No matching distribution found for vapi-client-bindings
> 
> I don't see anything in the requirements.txt that would point it to a different repo, unless I'm missing something.
> 
> I am running inside a virtual environment per recommendations in the docs, but the above pip3 command gives the same result regardless.

bindings and runtime are not in pypi. !!

**Comment by iuvooneill** [comment] 2021-12-08 18:33
I am having this issue currently as well.

**Comment by shwetapurohit** [comment] 2022-02-01 09:35
Closing this issue. 
If you are facing issue again, please feel free to reopen.

**Closed by shwetapurohit** 2022-02-01 09:35 UTC

**Comment by IAOTW** [comment] 2022-03-21 10:27
pip3 install pip-tools
thx for all!
