### ISSUE TITLE
Why no pip package?

### ISSUE THREAD

**Issue by stobias123** [vmware/vsphere-automation-sdk-python#201] opened 2020-01-07 14:49 UTC
Working behind a proxy right now, trying to get this installed is a nightmare. Why not just publish pip packages for packages in this repo? 

## Expected behavior
```
pip install vsphere-automation-sdk-python
```
## Actual Behavior
Lots of proxy issues with git, local installation dependencies via `--extra-index-url` flag

**Comment by mariolenz** [comment] 2020-01-08 18:24
This looks like a duplicate of #38.

**Comment by jobingeo** [comment] 2020-01-09 04:44
Right. This is duplicate of https://github.com/vmware/vsphere-automation-sdk-python/issues/38

We are looking into this. 
We need to have clearance for dependent packages before publishing to PyPi. 
Currently there is no ETA, which we can provide now

**Closed by jobingeo** 2020-01-09 04:44 UTC
