### ISSUE TITLE
Could not find a version that satisfies the requirement vapi-client-bindings==1.5.0 (from -r requirements.txt...)

### ISSUE THREAD

**Issue by dungla2011** [vmware/vsphere-automation-sdk-python#115] opened 2018-11-18 00:34 UTC
Help me please:

- [x ] I am using the https://github.com/vmware/vsphere-automation-sdk-python.git  (18/11/2018)
- [x ] I have searched [existing issues]

## Environment
- sdk package version: 
[root@galaxycloud vsphere-automation-sdk-python]# pip list | grep v
virtualenv 15.1.0

[root@galaxycloud vsphere-automation-sdk-python]# pip --version
pip 18.1 from /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pip (python 3.6)
[root@galaxycloud vsphere-automation-sdk-python]# python --version
Python 3.6.3

- vSphere version: 6.5

- Operating System/Shell (used to run SDK-based apps): Centos
## Steps or code snippet to reproduce

I have the this error:

```
[root@galaxycloud vsphere-automation-sdk-python]# pip install -r requirements.txt --extra-index-url /share/vsphere-automation-sdk-python/lib/
Ignoring suds: markers 'python_version < "3"' don't match your environment
Looking in indexes: https://pypi.org/simple, /share/vsphere-automation-sdk-python/lib/
Collecting pyVmomi>=6.7 (from -r requirements.txt (line 1))
  Url '/share/vsphere-automation-sdk-python/lib/pyvmomi/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/ee/9a/7b24db4501e720fbd0a3578a8dde4b03d20b6fc3427e992dce19a3cf5cfc/pyvmomi-6.7.1.zip
Collecting suds-jurko (from -r requirements.txt (line 3))
  Url '/share/vsphere-automation-sdk-python/lib/suds-jurko/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/bd/6f/54fbf0999a606680d27c69b1ad12dfff62768ecb9fe48524cebda6eb4423/suds-jurko-0.6.tar.bz2
Collecting tabulate (from -r requirements.txt (line 4))
  Url '/share/vsphere-automation-sdk-python/lib/tabulate/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Collecting vapi-client-bindings==1.5.0 (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement vapi-client-bindings==1.5.0 (from -r requirements.txt (line 5)) (from versions: 2.5.0)
No matching distribution found for vapi-client-bindings==1.5.0 (from -r requirements.txt (line 5))
You have mail in /var/spool/mail/root
```

**Requirements.txt:**
```
pyVmomi >= 6.7
suds ; python_version < '3'
suds-jurko ; python_version >= '3.0'
tabulate
vapi-client-bindings == 1.5.0
vmc-client-bindings
vapi-vmc-client
nsx-policy-python-sdk
vmc-app-python-sdk 
```

**Comment by tianhao64** [comment] 2018-11-19 02:30
Can you try: 
pip install -r requirements.txt --extra-index-url file:///share/vsphere-automation-sdk-python/lib/

**Comment by dungla2011** [comment] 2018-11-19 15:42
And after run something, it seem OK now: 
(Centos 7, Default Python 2.7.5)

[root@galaxycloud vsphere-automation-sdk-python]# python --version
Python 2.7.5

- Change in requirements.txt, from
vapi-client-bindings == 1.5.0 => vapi-client-bindings == 2.5.0

- Run some cmds:
pip install virtualenv
pip install wheel
pip install -r requirements.txt --extra-index-url file:///share/vsphere-automation-sdk-python/lib/

Seem ok  now (not show error)!

![image](https://user-images.githubusercontent.com/7878963/48717597-573bb300-ec4c-11e8-948b-5ee6eab329d4.png)


Hope help someone :)

**Comment by tianhao64** [comment] 2018-11-22 02:29
Added a troubleshooting wiki and describe the solution to this issue too. Closing as not a bug. Please let me know if you still can't install using the correct file path and pip parameters.

**Comment by tianhao64** [comment] 2018-11-22 02:30
Here is the wiki link: https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting#installation-raises-error-could-not-find-a-version-that-satisfies-the-requirement

**Closed by tianhao64** 2018-11-22 02:29 UTC

**Comment by Rajeev244** [comment] 2019-09-12 02:20
Getting the below error while installing virtualenv

C:\Users\Kishor4\Documents\GitHub\vsphere-automation-sdk-python>python.exe -m pip install virtualenvs
Collecting virtualenvs
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E28212FE48>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/virtualenvs/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E282EB10C8>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/virtualenvs/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E282EC00C8>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/virtualenvs/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E282EBE888>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/virtualenvs/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E282EBE848>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/virtualenvs/
  ERROR: Could not find a version that satisfies the requirement virtualenvs (from versions: none)
ERROR: No matching distribution found for virtualenvs

**Comment by sayhellotoelango** [comment] 2020-11-12 13:00
windows:
pip install -r requirements.txt --extra-index-url file:\\C:\Users\Administrator\Desktop\ovf\vsphere-automation-sdk-python\lib\

**Comment by mubarak-k** [comment] 2023-10-25 07:44
there is similar issue faced... 

 Could not find a version that satisfies the requirement vapi-runtime@ file://localhost//tmp/pip-esak4ple-build/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl   (from vsphere-automation-sdk==1.86.0) (from versions: )
No matching distribution found for vapi-runtime@ file://localhost//tmp/pip-esak4ple-build/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl (from vsphere-automation-sdk==1.86.0)

**Comment by shwetapurohit** [comment] 2023-10-25 07:58
@mubarak-k 
Please [find](https://github.com/vmware/vsphere-automation-sdk-python#installing-required-python-packages) SDK installation commands for different environment .
If you are still facing the issue,  please provide the steps to reproduce.

**Comment by rodmax** [comment] 2023-12-08 18:32
to install the package using `requirements.txt` you need put bellow string

```env
# requirements.txt
vsphere-automation-sdk @ git+https://github.com/vmware/vsphere-automation-sdk-python.git@v8.0.2.0
```

then
```bash
pip install -r requirerements.txt
```
