### ISSUE TITLE
Error when trying to list all the vm's running.

### ISSUE THREAD

**Issue by iamjhamukesh** [vmware/vsphere-automation-sdk-python#209] opened 2020-02-19 11:07 UTC
- [Y] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [Y] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [Y] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
nsx-vmc-aws-integration-python-sdk 2.5.1.0.1.15419398
nsx-vmc-policy-python-sdk          2.5.1.0.1.15419398
pyvmomi                            6.7.3
vapi-client-bindings               3.2.0
vapi-common-client                 2.14.0
vapi-runtime                       2.14.0
vconnector                         0.6.0
vmc-client-bindings                1.23.0
vmc-draas-client-bindings          1.3.0
vSphere-Automation-SDK             1.21.0

- python version: Python 3.7.6

- vSphere version: vSphere-Automation-SDK             1.21.0

- Operating System/Shell (used to run SDK-based apps): Mac OS(10.14.6)

## Steps or code snippet to reproduce

```
import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client
session = requests.session()

session.verify = False

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

vsphere_client = create_vsphere_client(server='aa.bbb.yyy.xxx', username='name@organisation.org', password=pwd, session=session)

print(vsphere_client.vcenter.VM.list())
```

## Actual behavior: 
```
Traceback (most recent call last):
  File "hosts.py", line 13, in <module>
    print(vsphere_client.vcenter.VM.list())
  File "/usr/local/lib/python3.7/site-packages/com/vmware/vcenter_client.py", line 5153, in list
    'filter': filter,
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 298, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: null', args=['null'], params=None, localized=None)], data : None, error_type : None}

```
## Expected behavior: 
All the Vm's should be listed up

However when I do this I get the bunch of VM's which are up. I don't know are they both doing same thing ?
```
from __future__ import print_function
from vconnector.core import VConnector
from config import *

client = VConnector(
     user='name@organisation.org',
     pwd=pwd,
     host='aa.bbb.yyy.xxx')
client.connect()
vms = client.get_vm_view()
print(vms.view)

client.disconnect()
```
Moreover in Vsphere - api explorer the code for fetching requests are also not given as well as no way to generate token.

**Comment by anusha94** [comment] 2020-02-19 12:21
I don't get the error with your code snippet.

Have you followed the installation steps correctly? https://github.com/vmware/vsphere-automation-sdk-python#installing-required-python-packages

**Comment by iamjhamukesh** [comment] 2020-02-19 12:28
Yep, I have configured things correctly. The issue seems to be in last line VM.list(). Because if I comment it, it works. I tried https://github.com/vmware/pyvmomi/blob/master/sample/getallvms.py this url and things worked. But not via current repo. Are both using same code base ?

**Comment by anusha94** [comment] 2020-02-19 12:32
Try this? https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/vm/list_vms.py

pyvmomi uses SOAP APIs whereas Automation SDK uses REST endpoints

**Comment by iamjhamukesh** [comment] 2020-02-19 12:36
Ya I had used this as well https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/vm/list_vms.py list_of_vms = self.client.vcenter.VM.list() code was breaking on this function. But when I used list_of_vms = self.client.vcenter.VM.list, it returned some object. I thought of checking the vcenter_client.py but didn't do

**Comment by anusha94** [comment] 2020-02-19 12:53
Can you try it in a new virtual environment? Not that what you have done is incorrect, just to make sure there are no conflicting versions.

**Comment by iamjhamukesh** [comment] 2020-02-19 13:04
Yes, I will do and update it. Most probably I can do this tomorrow.

**Comment by iamjhamukesh** [comment] 2020-02-19 13:41
Same error even when tried again in new venv

```
  File "file.py", line 18, in <module>
    print(vsphere_client.vcenter.VM.list())
  File "/Users/mukesh/Desktop/vcenter/sdk/sdk/lib/python3.7/site-packages/com/vmware/vcenter_client.py", line 5153, in list
    'filter': filter,
  File "/Users/mukesh/Desktop/vcenter/sdk/sdk/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/Users/mukesh/Desktop/vcenter/sdk/sdk/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 298, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: null', args=['null'], params=None, localized=None)], data : None, error_type : None}
```

**Comment by anusha94** [comment] 2020-02-19 13:54
what is your vsphere version?

**Comment by iamjhamukesh** [comment] 2020-02-19 14:14
6.7

**Comment by anusha94** [comment] 2020-02-20 10:14
@ngp-star can you check if you can reproduce this issue?

**Comment by anusha94** [comment] 2020-02-20 10:52
@iamjhamukesh 
Do you have any other VC setup that you can try on? Have you by any chance modified any permissions?

**Comment by iamjhamukesh** [comment] 2020-02-20 10:58
No, I don't have access to other VC setups and I haven't modified any permissions. But pyVim and pyVmomi is working perfectly for me. Only vmware.vapi.vsphere.client isn't working for me .

**Comment by ngp-star** [comment] 2020-02-24 07:11
Hi @iamjhamukesh 

 we tried with vc setup 67u1 version sample , its  working, able to list all vms.

**Comment by iamjhamukesh** [comment] 2020-02-25 08:56
I am facing same issue:

```
Traceback (most recent call last):
  File "sample.py", line 12, in <module>
    print(vsphere_client.vcenter.VM.list())
  File "/usr/local/lib/python3.7/site-packages/com/vmware/vcenter_client.py", line 5153, in list
    'filter': filter,
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 298, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: null', args=['null'], params=None, localized=None)], data : None, error_type : None}
```

**Comment by imokyoureok** [comment] 2020-03-18 11:52
I get the same error when trying to list VMs that are not assigned to a network and are therefore inaccessible. If I exclude the problematic VMs, then the API call works.

**Comment by anusha94** [comment] 2020-03-25 17:45
@iamjhamukesh is @imokyoureok 's scenario possible cause of error in your case?

**Comment by anusha94** [comment] 2020-04-20 10:57
@iamjhamukesh 
Any update?

**Comment by anusha94** [comment] 2020-04-23 07:37
closing this issue as there are no updates.

**Closed by anusha94** 2020-04-23 07:37 UTC

**Comment by ewan-derivco** [comment] 2020-04-24 10:08
wait!! we get the same issue, it errors when there are orphaned vms in the result set

**Comment by ewan-derivco** [comment] 2020-04-24 10:09
we are using the rest interface directly  via c# though so maybe not the python sdk at fault

**Comment by inshal96** [comment] 2020-08-25 05:09
Hi,

So when i apply the powered on filter, it lists all vms. When I remove that filter, it produces the following exception:

![image](https://user-images.githubusercontent.com/39904558/91125380-0f687c00-e6bb-11ea-832f-bdf1e9bf150f.png)

**Comment by dungla2011** [comment] 2020-08-25 11:29
> Hi,
> 
> So when i apply the powered on filter, it lists all vms. When I remove that filter, it produces the following exception:
> 
> ![image](https://user-images.githubusercontent.com/39904558/91125380-0f687c00-e6bb-11ea-832f-bdf1e9bf150f.png)

If it has any unaccessable, obsolete vm on vcenter?

**Comment by inshal96** [comment] 2020-08-25 16:08
Yes, it did have an obsolete vm.

**Comment by inshal96** [comment] 2020-08-25 16:08
> > Hi,
> > So when i apply the powered on filter, it lists all vms. When I remove that filter, it produces the following exception:
> > ![image](https://user-images.githubusercontent.com/39904558/91125380-0f687c00-e6bb-11ea-832f-bdf1e9bf150f.png)
> 
> If it has any unaccessable, obsolete vm on vcenter?

Yes, it did have an obsolete vm.

**Comment by yanglijian201** [comment] 2021-04-13 01:58
Almost a year, issue still there....Quite easy to reproduce, what are you doing VMware, my lover?

**Comment by shwetapurohit** [comment] 2022-03-16 07:39
@jhamukesh998 

Could you please share the vc bundle, i'm not able to reproduce the issue
